deployment:
  name: frontend-deployment
  replicas: 1

image:
  repository: kalpak44/craftify-app
  tag: "latest"

service:
  name: frontend-service

ingress:
  name: frontend-ingress
  host: app.craftyfy.pro
  secretName: app-craftyfy-pro-tls

redirectIngress:
  host: app.craftyfy.pro
