apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  labels:
    app: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          ports:
            - containerPort: 9000
              hostPort: 8081
          env:
            - name: KAFKA_BROKERCONNECT
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  labels:
    name: kafdrop
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 9000
      name: kafdrop
      protocol: TCP
  selector:
    app: kafka
