apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
  namespace: userspace
  labels:
    app: kafka-producer
spec:
  restartPolicy: Never
  containers:
    - name: producer
      image: edenhill/kcat:1.7.1
      command: [ "sh", "-c", "sleep 3600" ]
