apiVersion: v1
kind: Pod
metadata:
  name: network-debug
  namespace: userspace
  labels:
    app: debug
spec:
  containers:
    - name: multitool
      image: praqma/network-multitool
      command: [ "sh", "-c", "sleep 3600" ]
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
