apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: router-scaler
  namespace: userspace
spec:
  scaleTargetRef:
    name: router
  minReplicaCount: 0
  maxReplicaCount: 1
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka.kafka.svc:9092
      topic: event-topic
      consumerGroup: router-consumer
      lagThreshold: "1"
