# Minimal ERPNext values.yaml for Docker Desktop Kubernetes (using hostpath storage)

image:
  repository: frappe/erpnext
  tag: v15.72.1
  pullPolicy: IfNotPresent

nginx:
  replicaCount: 1
  autoscaling:
    enabled: false
  environment:
    upstreamRealIPAddress: "127.0.0.1"
    proxyReadTimeout: "120"
    clientMaxBodySize: "50m"
  livenessProbe:
    tcpSocket:
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
  readinessProbe:
    tcpSocket:
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
  service:
    type: ClusterIP
    port: 8080

worker:
  gunicorn:
    replicaCount: 1
    autoscaling:
      enabled: false
    livenessProbe:
      tcpSocket:
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      tcpSocket:
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 10
    service:
      type: ClusterIP
      port: 8000

  default:
    replicaCount: 1
    autoscaling:
      enabled: false

  short:
    replicaCount: 1
    autoscaling:
      enabled: false

  long:
    replicaCount: 1
    autoscaling:
      enabled: false

  scheduler:
    replicaCount: 1

socketio:
  replicaCount: 1
  autoscaling:
    enabled: false
  livenessProbe:
    tcpSocket:
      port: 9000
    initialDelaySeconds: 5
    periodSeconds: 10
  readinessProbe:
    tcpSocket:
      port: 9000
    initialDelaySeconds: 5
    periodSeconds: 10
  service:
    type: ClusterIP
    port: 9000

persistence:
  worker:
    enabled: true
    size: 1Gi
    accessModes:
      - ReadWriteOnce
    storageClass: hostpath   # <-- Make sure this matches your storageclass!
  logs:
    enabled: false
    size: 1Gi
    accessModes:
      - ReadWriteOnce
    storageClass: hostpath   # <-- Same here

ingress:
  enabled: false
  hosts:
    - host: erp.cluster.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

jobs:
  configure:
    enabled: true
    fixVolume: true

  createSite:
    enabled: true
    forceCreate: true
    siteName: "localhost"
    adminPassword: "admin"
    installApps:
      - "erpnext"
    dbType: "mariadb"

redis-cache:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    containerPorts:
      redis: 6379
    persistence:
      enabled: false

redis-queue:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    containerPorts:
      redis: 6379
    persistence:
      enabled: false

mariadb:
  enabled: true
  auth:
    rootPassword: "root"
    username: "erpnext"
    password: "erpnext"
    replicationPassword: "repl"
  primary:
    service:
      ports:
        mysql: 3306
    extraFlags: >-
      --skip-character-set-client-handshake
      --skip-innodb-read-only-compressed
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

postgresql:
  enabled: false

serviceAccount:
  create: true

podSecurityContext:
  supplementalGroups: [1000]

securityContext:
  capabilities:
    add:
      - CAP_CHOWN
