# Server configuration
server:
  # Maximum size of HTTP request headers
  max-http-request-header-size: 40960
  # Enable graceful shutdown
  shutdown: graceful
  # Server port
  port: 8080
  # HTTP response compression settings
  compression:
    enabled: true
    # MIME types to be compressed
    mime-types: text/xml,text/plain,application/json
    # Minimum response size to trigger compression
    min-response-size: 1024

#logging:
#  level:
#    org.springframework: INFO
#    com.craftify: INFO
#  pattern:
#    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
#    file: "%d %p %c{1.} [%t] %m%n"
#  file:
#    name: "logger.log"
#  logback:
#    rollingpolicy:
#      max-file-size: 100MB
#      max-history: 10

# Spring configuration
  data:
    mongodb:
      # MongoDB URI with placeholders for environment variables
      uri: ${MONGO_CONNECTION_STRING:}
  jpa:
    properties:
      # Ensure the JDBC time zone is set to UTC
      jdbc:
        time_zone: UTC

# Springdoc configuration for OpenAPI and Swagger UI
springdoc:
  api-docs:
    # Path for API documentation
    path: '/v3/api-docs'
  swagger-ui:
    # Path for Swagger UI
    path: '/swagger-ui'
    # Sort operations alphabetically
    operationsSorter: alpha
    # Sort tags alphabetically
    tagsSorter: alpha

app:
  cors:
    allowed-origins:
      - http://localhost:5173

# Auth0 configuration
okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: ${AUTH0_ISSUER}
    # Replace with the API Identifier for your Auth0 API.
    audience: ${AUTH0_AUDIENCE}

# Kubernetes client configuration
kubernetes:
  master-url: https://localhost:6443
  trust-certs: true