apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: AUTH0_AUDIENCE
              value: "{{ .Values.env.AUTH0_AUDIENCE }}"
            - name: AUTH0_ISSUER
              value: "{{ .Values.env.AUTH0_ISSUER }}"
            - name: MONGO_CONNECTION_STRING
              value: "{{ .Values.env.MONGO_CONNECTION_STRING }}"
