name: Build, Push Docker Image, and Deploy with Helm

on:
  push:
    paths-ignore:
      - 'craftify-app/**'
      - '.pipelines/deployments/frontend/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            kalpak44/craftify-backend-api:latest
            kalpak44/craftify-backend-api:${{ github.sha }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Set up Kubernetes config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Deploy with Helm
        run: |
          helm upgrade --install backend ./.pipelines/deployments/backend \
            --set image.repository=kalpak44/craftify-backend-api \
            --set image.tag=${{ github.sha }} \
            --set env.AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }} \
            --set env.AUTH0_ISSUER=${{ secrets.AUTH0_ISSUER }} \
            --set env.MONGO_CONNECTION_STRING=${{ secrets.MONGO_CONNECTION_STRING }}
